- name: Launch EC2 instance without key pair
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: us-east-1
    ami_id: ami-09c813fb71547fc4f  # Replace with latest Amazon Linux 2 AMI in your region
    instance_type: t2.micro
    subnet_id: subnet-0f15782134914e097      # Replace with your subnet ID
    security_group_id: sg-0354f0db2462dba79  # Replace with your security group ID
    instance_name: my-ec2-instance
    instance_count: 1

  tasks:
  - name: Launch EC2 instance without key pair
    amazon.aws.ec2_instance:
      name: "{{ instance_name }}"
      region: "{{ region }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
      count: "{{ instance_count }}"
      wait: true
      key_name: ""  # No key pair
      vpc_subnet_id: "{{ subnet_id }}"
      security_group: "{{ security_group_id }}"
      tags:
         Name: "{{ instance_name }}"
         CreatedBy: Ansible
      register: ec2_result

  - name: Show EC2 instance info
    debug:
      var: ec2_result.instances
